image: maven:3.9-eclipse-temurin-21

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - test
  - build

cache:
  paths:
    - .m2/repository

unit-tests:
  stage: test
  script:
    - mvn test

build-app:
  stage: build
  script:
    - mvn package -DskipTests

